{"uuid": "b638099f-e339-4df0-8efa-7b98d3b6bea8", "children": ["0bdd4e81-e6e8-449b-91b6-1d3a912c8f58", "34b0216a-007e-452c-8e94-43a6f8d5c12a", "93518eae-2b3f-4621-bb1e-3cfd775595b5", "793d7348-4015-4343-9fb8-0bbf486ff209"], "befores": [{"name": "driver", "status": "passed", "start": 1693404318444, "stop": 1693404323701}], "afters": [{"name": "driver::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: Must either pass base64 data or a local file path\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 209, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 916, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/yaroslav.petryk/Desktop/projects/testrail_android/tests/conftest.py\", line 21, in driver\n    appium_driver.push_file('./tests/config.json')\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/appium/webdriver/extensions/remote_fs.py\", line 80, in push_file\n    raise InvalidArgumentException('Must either pass base64 data or a local file path')\n"}, "start": 1693404368566, "stop": 1693404368582}], "start": 1693404318444, "stop": 1693404368582}